services:
  app:
    image: dashboard-osdop:latest
    ports:
      - "3000:3000"
    environment:
      ULTRAVOX_API_KEY: "${ULTRAVOX_API_KEY}"
      PORT: "3000"
    volumes:
      - ./data:/app/data
    networks:
      - mateo
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=mateo"
        - "traefik.http.routers.osdop.rule=Host(`dashboard.mateoia.store`)"
        - "traefik.http.routers.osdop.entrypoints=websecure"
        - "traefik.http.routers.osdop.tls=true"
        - "traefik.http.routers.osdop.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.osdop.loadbalancer.server.port=3000"

networks:
  mateo:
    external: true
