version: '3.8'
services:
  dashboard-osdop:
    build: .
    image: dashboard-osdop:latest
    ports:
      - "5174:80"
    environment:
      - VITE_ULTRAVOX_KEY=MnO6Ztj0.GgITCvEoij1dLRgGTFWemaNCwZtHhZ9c
      - PORT=80
    deploy:
      restart_policy:
        condition: any
