server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ultravox/ {
        proxy_pass https://api.ultravox.ai/api/;
        proxy_set_header Host api.ultravox.ai;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-API-Key "MnO6Ztj0.GgITCvEoij1dLRgGTFWemaNCwZtHhZ9c";
        
        # Bypassing CORS by having the server make the request
        proxy_ssl_server_name on;
    }
}
